### ISSUE TITLE
DM5 Vehicle Composite Summary Incorrect

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/iumpr#33]
The Diagnostic Readiness Packet is ignoring the OBD Compliances.  Thus the tests are being interpreted when the module is not OBD Compliant.

**Comment by joekartje** [comment]
The original form submitted for this issue is posted on the Google Drive:
https://drive.google.com/open?id=0BzIQ48EeW5tTVG1xZTZLSGlQTVk
It was subdivided into an issue for the error:
https://drive.google.com/open?id=0BzIQ48EeW5tTOWxqNzRVUDl6UUE
and another issue for the display improvement:
https://drive.google.com/open?id=0BzIQ48EeW5tTWXkzMl90Uld4bE0
