### ISSUE TITLE
No confirmation that DM11 was successful

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#43]
ARB staff began the IUMPR version 0.6.2 program with the engine running (key on-engine ON); this did not result in clearing DTCs/resetting the time since DTCs.

From Eric Swenson:
"Looking at the Java this weekend I noticed that the logic says response == .nack (1).  A better construct may be to say <> .ack (0).  A running engine clearly has leave in SAE J1939-73 5.7.11 to say Access Denied (2) or Busy (3) in addition to NACK, whether the engine is running or not.  Since there is a long tradition where there are no responses provided for global requests, waiting 5 seconds for <> 0, has the hole demonstrated by ARB.  Checking Time SCC when “File := new File <handle>” may be the best we can hope to do.  "

Does this require a software change, or can it be address with an update to the HELP file (i.e., "IUMPR Application must be started with key on-engine OFF")?

The submitted issue form can be found at https://drive.google.com/open?id=0BzIQ48EeW5tTeWFpQklDRVdsWEU

**Comment by gumbelmj** [comment]
We need to determine how best to resolve this issue and there may be many resolutions put into place.
1. We can adjust the logic for determining when a successful DM11 response has been received as suggested by Eric.
2. We could change the logic to check the Time Since Code Clear after requesting a DM11 to ensure the codes were reset.
3. We could add a pop up to remind the user to turn the engine off.
3B. We could only display the pop up if the engine is actually running just before requesting the DM11 or starting the Generate Data Plate function
4. We could address the issue in the Help File.

Furthermore, we might consider this to be an enhancement rather than a bug as I believe it does function as we were directed to implement it.

**Comment by joekartje** [comment]
Proposed resolution:
1) Update Help file (Eric and I will determine the verbiage.)
2) Change current logic to response <> .ack (0)
3) Simple popup reminder to have "Key On, Engine Off" at the start of the test.  Display the pop up if the engine is actually running just before requesting the DM11 or starting the Generate Data Plate function.

**Comment by gumbelmj** [comment]
The help file still needs updated.

**Comment by joekartje** [comment]
Help file updated.
