### ISSUE TITLE
Task 8 Proposal — Update Logging Methods with J1939-84 project lessons learned  

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/iumpr#86]
Replace exiting logging methods with best practices learned during the J1939-84 projects.

**Comment by battjt** [comment]
Update RP1210 connection, moving J1939-21 TP into the application, so that logs will include the fragments and warnings about TP errors.  This also include updates to the UI to support the user specifying the RP1210 "connection string".
![image](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/1972001/5d4f7add-2914-4d04-be93-5cdd15425edf)

**Comment by battjt** [comment]
Updated UI to use larger fonts and 1080p sized screen:
![image](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/1972001/ca3fe62c-d4ab-4fbb-ac02-bcf42a462f89)

**Comment by ericthomasswenson** [comment]
IUMPR Complete for Task 8
